export const AUTHENTICATION_ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  WAS_NOT_POSSIBLE_TO_CREATE_USER: 'WAS_NOT_POSSIBLE_TO_CREATE_USER',
  PASSWORD_MIN_8_CHARACTERS: 'PASSWORD_MIN_8_CHARACTERS',
  UNAUTHORIZED_AUTHENTICATION_HEADER_NOT_FOUND: 'UNAUTHORIZED_AUTHENTICATION_HEADER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
}