export const FIELD_ERROR_MESSAGES = {
  REQUIRED: 'FIELD_ERROR_REQUIRED',
  INVALID_FIELD: 'FIELD_ERROR_INVALID',
  MAX_LENGTH(length: number) {
    return `FIELD_ERROR_MAX_LENGTH_${length}`;
  },
  DATE_MUST_BE_IN_FUTURE: 'DATE_MUST_BE_IN_FUTURE'
}