export const FIELD_ERROR_MESSAGES = {
  REQUIRED: 'FIELD_ERROR_REQUIRED',
  INVALID_FIELD: 'FIELD_ERROR_INVALID',
  UNAUTHORIZED_AUTHENTICATION_HEADER_NOT_FOUND: 'UNAUTHORIZED_AUTHENTICATION_HEADER_NOT_FOUND',
  MAX_LENGTH(length: number) {
    return `FIELD_ERROR_MAX_LENGTH_${length}`;
  },
  MAX_VALUE(value: number) {
    return `FIELD_ERROR_MAX_VALUE_${value}`;
  },
  DATE_MUST_BE_IN_FUTURE: 'DATE_MUST_BE_IN_FUTURE'
}