export const URL_ERRORS = {
  SHORT_URL_ALREADY_EXISTS: 'SHORT_URL_ALREADY_EXISTS',
  WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL: 'WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL',
  URL_NOT_FOUND: 'URL_NOT_FOUND',
  ONLY_2_URL_CREATIONS_PER_HOUR: 'ONLY_2_URL_CREATIONS_PER_HOUR',
}