export const URL_ERRORS = {
  SHORT_URL_ALREADY_EXISTS: 'SHORT_URL_ALREADY_EXISTS',
  WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL: 'WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL',
  URL_NOT_FOUND: 'URL_NOT_FOUND',
  ONLY_1_URL_CREATIONS_PER_DAY: 'ONLY_1_URL_CREATIONS_PER_DAY',
  URL_ALREADY_DELETED: 'URL_ALREADY_DELETED',
  MONTHLY_LINK_LIMIT_REACHED: 'MONTHLY_LINK_LIMIT_REACHED',
}