export const URL_ERRORS = {
  SHORT_URL_ALREADY_EXISTS: 'SHORT_URL_ALREADY_EXISTS',
  WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL: 'WAS_NOT_POSSIBLE_TO_CREATE_SHORT_URL',
  URL_NOT_FOUND: 'URL_NOT_FOUND',
  ONLY_1_URL_CREATIONS_PER_DAY: 'ONLY_1_URL_CREATIONS_PER_DAY',
  URL_ALREADY_DELETED: 'URL_ALREADY_DELETED',
  MONTHLY_LINK_LIMIT_REACHED: 'MONTHLY_LINK_LIMIT_REACHED',
  DAILY_LINK_LIMIT_REACHED: 'DAILY_LINK_LIMIT_REACHED',
  MONTHLY_QR_CODE_LIMIT_REACHED: 'MONTHLY_QR_CODE_LIMIT_REACHED',
  ONLY_50_QR_CODE_PREVIEWS_PER_HOUR: 'ONLY_50_QR_CODE_PREVIEWS_PER_HOUR',
  QR_CODE_PREVIEW_NOT_AVAILABLE_ON_FREE_PLAN: 'QR_CODE_PREVIEW_NOT_AVAILABLE_ON_FREE_PLAN',
  QR_CODE_NOT_GENERATED: 'QR_CODE_NOT_GENERATED'
}